org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.222
mod_id=create_mf
mod_name=Create: More Features Patched Unofficial
mod_version=0.9.69-patched-unofficial
mod_group_id=net.mcreator.create_mf
mod_authors=Daniil_White, Tamlighter, Yankeevader patch
mod_license=Academic Free License v3.0
